version: '2'
services:
  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'lyrics'
      MYSQL_PASSWORD: 'pass'
    volumes:
      - my-datavolume:/Users/qianzecheng/Documents/GitHub/mysql-crash-course/mysql
volumes:
  my-datavolume: